// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPro.Core.Api.Brokers.Storages;

#nullable disable

namespace UPro.Core.Api.Migrations
{
    [DbContext(typeof(StorageBroker))]
    partial class StorageBrokerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UPro.Core.Api.Models.Settings.CompanyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("CompanyLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CompanyLogoPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FictitiousBusinessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelephoneAlternate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CompanyProfiles", "Settings");
                });

            modelBuilder.Entity("UPro.Core.Api.Models.Settings.CompanyProfileDefault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CurrentPeriodGLID")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultAPGL")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultAPGLBank")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultARCreditLiability")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultARGL")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultARGLBank")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultInventoryGL")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultPRBankAccount")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultRevenueGL")
                        .HasColumnType("int");

                    b.Property<string>("EmployerIdentificationNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EndingInventory")
                        .HasColumnType("int");

                    b.Property<string>("FirstMonthFiscalYear")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InventoryCostingMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("LastGLStartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastGLStopDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastGLType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastPeriodClosedMonth")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LastPeriodClosedYear")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StateTaxID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("SumAP")
                        .HasColumnType("bit");

                    b.Property<bool>("SumAPPayments")
                        .HasColumnType("bit");

                    b.Property<bool>("SumAR")
                        .HasColumnType("bit");

                    b.Property<bool>("SumARPayments")
                        .HasColumnType("bit");

                    b.Property<bool>("SumJE")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId")
                        .IsUnique();

                    b.ToTable("CompanyProfileDefaults", "Settings");
                });

            modelBuilder.Entity("UPro.Core.Api.Models.Settings.CompanyProfileDefault", b =>
                {
                    b.HasOne("UPro.Core.Api.Models.Settings.CompanyProfile", "CompanyProfile")
                        .WithOne("ProfileDefaults")
                        .HasForeignKey("UPro.Core.Api.Models.Settings.CompanyProfileDefault", "CompanyProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("UPro.Core.Api.Models.Settings.CompanyProfile", b =>
                {
                    b.Navigation("ProfileDefaults");
                });
#pragma warning restore 612, 618
        }
    }
}
